name: Android Pull Request & Master CI

on:
  push:
    branches:
      - 'master'
      - 'develop'

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Unit tests
        run: bash ./gradlew testDebugUnitTest --stacktrace


